# Generated by Django 4.2 on 2023-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата записи')),
            ],
        ),
    ]
